version: "2"
services:
  # owner server self-signed certificate for communication with wonnode
  gencert:
    build: ../../image/gencert
    #image: webofneeds/gencert:master
    environment:
      - "CN=hackathon.matchat.org"
      - "PASS=file:/usr/local/certs/out/won_certificate_passwd_file"
      - "OPENSSL_CONFIG_FILE=/usr/local/openssl.conf"
    volumes:
      - $base_folder/won-server-certshackathon:/usr/local/certs/out/
      - $base_folder/openssl.conf:/usr/local/openssl.conf

  # portsgres atom databases for owner and wonnode
  postgres:
    restart: always
    #image: webofneeds/postgres:master
    build: ../../image/postgres
    environment:
      - "POSTGRES_PASSWORD=$postgres_db_passwd"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    volumes:
      - $base_folder/postgres/data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5434:5432"

  # wonnode => https://hackathonnode.matchat.org/won
  wonnode:
    restart: always
    build: ../../image/wonnode
    #image: webofneeds/wonnode:master
    environment:
      - "URI_HOST=hackathonnode.matchat.org"
      - "HTTP_PORT=8890"
      - "URI_PREFIX=https://hackathonnode.matchat.org/won"
      - "CLIENT_AUTHENTICATION_BEHIND_PROXY=true"
      - "DB_SQL_JDBCDRIVERCLASS=org.postgresql.Driver"
      - "DB_SQL_JDBCURL=jdbc:postgresql://satvm02.researchstudio.at:5434/won_node"
      - "DB_DDL_STRATEGY=validate"
      - "DB_SQL_USER=won"
      - "DB_SQL_PASSWORD=$postgres_db_passwd"
      - "CERTIFICATE_PASSWORD=$won_certificate_passwd"
      - "ACTIVEMQ_BROKER_PORT=61613"
      - "JMEM_OPTS=-XX:+HeapDumpOnOutOfMemoryError"
      - "JMX_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,address=*:62924,server=y,suspend=n
        -Dcom.sun.management.jmxremote.port=9030 -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=9030
        -Djava.rmi.server.hostname=satvm02.researchstudio.at"
    ports:
      - "8890:8443"
      - "61623:61613"
      - "62924:62924"
      - "9030:9030"
    volumes:
      - $base_folder/letsencrypt/certs/live/matchat.org/fullchain.pem:/usr/local/tomcat/conf/ssl/t-cert.pem
      - $base_folder/letsencrypt/certs/live/matchat.org/privkey.pem:/usr/local/tomcat/conf/ssl/t-key.pem
      - $base_folder/letsencrypt/certs/live/matchat.org/t-key-cert.pfx:/usr/local/tomcat/conf/ssl/t-key-cert.pfx
      - $base_folder/letsencrypt/certs/live/matchat.org/t-keystore.jks:/usr/local/tomcat/conf/ssl/t-keystore.jks
      - $base_folder/won-client-certs/hackathonnode:/usr/local/tomcat/won/client-certs/
    depends_on:
      - postgres
      - gencert

  # owner => https://hackathon.matchat.org/owner
  owner:
    restart: always
    build: ../../image/owner
    #image: webofneeds/owner:master
    environment:
      - "NODE_DEFAULT_HOST=hackathonnode.matchat.org"
      - "URI_HOST=hackathon.matchat.org"
      - "HTTP_PORT=8083"
      - "NODE_DEFAULT_HTTP_PORT=443"
      - "URI_PREFIX=https://hackathon.matchat.org"
      - "URI_PREFIX_NODE_DEFAULT=https://hackathonnode.matchat.org/won"
      - "DB_SQL_JDBCDRIVERCLASS=org.postgresql.Driver"
      - "DB_SQL_JDBCURL=jdbc:postgresql://satvm02.researchstudio.at:5434/won_owner"
      - "DB_DDL_STRATEGY=validate"
      - "DB_SQL_USER=won"
      - "DB_SQL_PASSWORD=$postgres_db_passwd"
      - "CERTIFICATE_PASSWORD=$won_certificate_passwd"
      - "EMAIL_FROM_WON_USER=$MAIL_USER"
      - "EMAIL_FROM_WON_PASSWORD=$MAIL_PASS"
      - "EMAIL_FROM_WON_SMTP_HOST=$MAIL_HOST"
      - "JMEM_OPTS=-XX:+HeapDumpOnOutOfMemoryError"
      - "JMX_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,address=*:62926,server=y,suspend=n
        -Dcom.sun.management.jmxremote.port=9031 -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=9031
        -Djava.rmi.server.hostname=satvm02.researchstudio.at"
    ports:
      - "8083:8443"
      - "62926:62926"
      - "9031:9031"
    volumes:
      - $base_folder/custom_owner_skin:/usr/local/tomcat/webapps/owner/skin/current/
      - $base_folder/won-server-certshackathon:/usr/local/tomcat/conf/ssl/
      - $base_folder/won-client-certs/hackathon:/usr/local/tomcat/won/client-certs/
    depends_on:
      - wonnode
      - postgres
      - gencert

  # #mongodb for persistent debug bot
  # mongodb:
  #   restart: always
  #   image: tutum/mongodb:3.2
  #   environment:
  #     - "MONGODB_USER=won"
  #     - "MONGODB_DATABASE=hackathon_bot"
  #     - "MONGODB_PASS=$mongo_db_passwd"
  #   ports:
  #     - "27019:27017"
  #     - "28019:28017"
  #   volumes:
  #     - $base_folder/mongodb/data/db:/data/db

  # bigdata rdf store for matcher service (this image is not built at deployment, it is downloaded from dockerhub)
  bigdata:
    restart: always
    build: ../../image/bigdata
    volumes:
      - $base_folder/bigdata/data:/usr/src/bigdata/data/
    ports:
      - "10000:9999"

  # matcher service connect with hackathonnode
  matcher_service:
    restart: always
    build: ../../image/matcher-service
    #image: webofneeds/matcher_service:master
    environment:
      - "NODE_HOST=satvm02.researchstudio.at"
      - "MATCHER_URI=https://hackathon.matchat.org/matcher_service" # set this for the trust store alias
      - "CLUSTER_SEEDNODES=satvm02.researchstudio.at:2555"
      - "URI_SPARQL_ENDPOINT=http://satvm02.researchstudio.at:10000/blazegraph/namespace/kb/sparql"
      - "WONNODECONTROLLER_WONNODE_CRAWL=https://hackathonnode.matchat.org/won/resource"
      - "CLUSTER_LOCAL_PORT=2555"
      - "JMEM_OPTS=-XX:+HeapDumpOnOutOfMemoryError"
      - "JMX_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,address=*:62927,server=y,suspend=n
        -Dcom.sun.management.jmxremote.port=9024 -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=9024
        -Djava.rmi.server.hostname=satvm02.researchstudio.at"
    ports:
      - "2555:2555"
      - "62927:62927"
      - "9024:9024"
    volumes:
      - $base_folder/won-client-certs/matcher_service:/usr/src/matcher-service/client-certs/
    depends_on:
      - bigdata
      - wonnode

  # solr server as an atom index
  # solr:
  #   restart: always
  #   build: ../../image/solr
  #   image: webofneeds/solr:master
  #   volumes:
  #     - $base_folder/solr/won/data:/opt/solr/server/solr/won/data
  #     - $base_folder/solr/wontest/data:/opt/solr/server/solr/wontest/data
  #   ports:
  #     - "8983:8983"
  # solr matcher and connect to matcher service
  # matcher_solr:
  #   restart: always
  #   build: ../../image/matcher-solr
  #   image: webofneeds/matcher_solr:master
  #   environment:
  #     - "NODE_HOST=satvm02.researchstudio.at"
  #     - "CLUSTER_SEEDNODES=satvm02.researchstudio.at:2551,satvm02.researchstudio.at:2552"
  #     - "CLUSTER_LOCAL_PORT=2552"
  #     - "MATCHER_SOLR_URI_SOLR_SERVER=http://satvm02.researchstudio.at:8983/solr/"
  #     - "MATCHER_SOLR_URI_SOLR_SERVER_PUBLIC=http://satvm02.researchstudio.at:8983/solr/"
  #     - "JMEM_OPTS=-XX:+HeapDumpOnOutOfMemoryError"
  #     - "JMX_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,address=*:62921,server=y,suspend=n
  #       -Dcom.sun.management.jmxremote.port=9021 -Dcom.sun.management.jmxremote.authenticate=false
  #       -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=9021
  #       -Djava.rmi.server.hostname=satvm02.researchstudio.at"
  #   ports:
  #     - "2552:2552"
  #     - "9021:9021"
  #     - "62921:62921"
  #   depends_on:
  #     - solr
  #     - matcher_service

  matcher_sparql:
    restart: always
    build: ../../image/matcher-sparql
    #image: webofneeds/matcher_sparql:int
    environment:
      - "NODE_HOST=satvm02.researchstudio.at"
      - "CLUSTER_SEEDNODES=satvm02.researchstudio.at:2555"
      - "CLUSTER_LOCAL_PORT=2556"
      - "MATCHER_SPARQL_URI_SPARQL_ENDPOINT=http://satvm02.researchstudio.at:10000/blazegraph/namespace/kb/sparql"
      - "MATCHER_SPARQL_URI_PUBLIC=http://satvm02.researchstudio.at/hackathonsparql/"
      - "JMEM_OPTS=-XX:+HeapDumpOnOutOfMemoryError"
      - "JMX_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,address=*:62925,server=y,suspend=n
        -Dcom.sun.management.jmxremote.port=9025 -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=9025
        -Djava.rmi.server.hostname=satvm02.researchstudio.at"
    ports:
      - "2556:2556"
      - "9025:9025"
      - "62925:62925"
    depends_on:
      - matcher_service
    volumes:
      - $base_folder/won-client-certs/matcher_sparql:/usr/src/matcher-sparql/client-certs/
