version: '2'
services:

  # owner server self-signed certificate for communication with wonnode
  gencert:
    restart: always
    build: ../../image/gencert
    environment:
      - "CN=cbi.matchat.org"
      - "PASS=file:/usr/local/certs/out/uki_certificate_passwd_file"
      - "OPENSSL_CONFIG_FILE=/usr/local/openssl.conf"
    volumes:
      - $base_folder/won-server-certs:/usr/local/certs/out/
      - $base_folder/openssl.conf:/usr/local/openssl.conf

  # postgres atom databases for wonnode
  postgres_node:
    restart: always
    build: ../../image/postgres
    environment:
      - "POSTGRES_PASSWORD=$postgres_db_passwd"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    volumes:
      - $base_folder/postgres_node/data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"

  # wonnode with nginx proxy => https://line.uki.or.at/won
  wonnode:
    restart: always
    build: ../../image/wonnode
    environment:
      - "URI_HOST=cbi.matchat.org"
      - "URI_PREFIX=https://cbi.matchat.org/won"
      - "HTTP_PORT=8443"
      - "DB_SQL_JDBCDRIVERCLASS=org.postgresql.Driver"
      - "DB_SQL_JDBCURL=jdbc:postgresql://satvm06.researchstudio.at:5433/won_node"
      - "DB_DDL_STRATEGY=validate"
      - "DB_SQL_USER=won"
      - "DB_SQL_PASSWORD=$postgres_db_passwd"
      - "CERTIFICATE_PASSWORD=$uki_certificate_passwd"
      - "ACTIVEMQ_BROKER_PORT=61626"
      - "CLIENT_AUTHENTICATION_BEHIND_PROXY=true"
      - "JMEM_OPTS=-XX:+HeapDumpOnOutOfMemoryError"
    ports:
      - "8443:8443"
      - "61627:61626"
    volumes:
      - $base_folder/letsencrypt/certs/live/cbi.matchat.org/fullchain.pem:/usr/local/tomcat/conf/ssl/t-cert.pem
      - $base_folder/letsencrypt/certs/live/cbi.matchat.org/privkey.pem:/usr/local/tomcat/conf/ssl/t-key.pem
      - $base_folder/letsencrypt/certs/live/cbi.matchat.org/t-key-cert.pfx:/usr/local/tomcat/conf/ssl/t-key-cert.pfx
      - $base_folder/letsencrypt/certs/live/cbi.matchat.org/t-keystore.jks:/usr/local/tomcat/conf/ssl/t-keystore.jks
      - $base_folder/won-client-certs/wonnode:/usr/local/tomcat/won/client-certs/
    depends_on:
      - postgres_node

  # postgres atom databases for owner
  postgres_owner:
    restart: always
    build: ../../image/postgres
    environment:
      - "POSTGRES_PASSWORD=$postgres_db_passwd"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    volumes:
      - $base_folder/postgres_owner/data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  # owner with nginx proxy (https://line.uki.or.at/owner)
  # TODO change the node uri from node.matchat.org/won to the new meicogsci node url once it is there
  owner:
    restart: always
    build: ../../image/owner
    environment:
      - "NODE_DEFAULT_HOST=cbi.matchat.org"
      - "URI_HOST=cbi.matchat.org"
      - "HTTP_PORT=8082"
      - "NODE_DEFAULT_HTTP_PORT=443"
      - "URI_PREFIX=https://cbi.matchat.org"
      - "URI_PREFIX_NODE_DEFAULT=https://node.matchat.org/won"
      - "DB_SQL_JDBCDRIVERCLASS=org.postgresql.Driver"
      - "DB_SQL_JDBCURL=jdbc:postgresql://satvm06.researchstudio.at:5432/won_owner"
      - "DB_DDL_STRATEGY=validate"
      - "DB_SQL_USER=won"
      - "DB_SQL_PASSWORD=$postgres_db_passwd"
      - "CERTIFICATE_PASSWORD=$uki_certificate_passwd"
      - "OWNER_WEBAPP_REMEMBERME_KEY=$rememberme_key"
      - "EMAIL_FROM_WON_USER=$MAIL_USER"
      - "EMAIL_FROM_WON_PASSWORD=$MAIL_PASS"
      - "EMAIL_FROM_WON_SMTP_HOST=$MAIL_HOST"
      - "JMEM_OPTS=-XX:+HeapDumpOnOutOfMemoryError"
    ports:
      - "8082:8443"
    volumes:
      - $base_folder/custom_owner_skin:/usr/local/tomcat/webapps/owner/skin/current/
      - $base_folder/won-server-certs:/usr/local/tomcat/conf/ssl/
      - $base_folder/won-client-certs/owner:/usr/local/tomcat/won/client-certs/
    depends_on:
      - postgres_owner
      - gencert

  # bigdata rdf store for matcher service (this image is not built at deployment, it is downloaded from dockerhub)
  bigdata:
    restart: always
    build: ../../image/bigdata
    volumes:
      - $base_folder/bigdata/data/:/usr/src/bigdata/data
    ports:
      - "10000:9999"

  # matcher service connect with wonnode on line.uki.or.at and node.matchat.org
  matcher_service:
    restart: always
    build: ../../image/matcher-service
    environment:
      - "NODE_HOST=satvm06.researchstudio.at"
      - "MATCHER_URI=https://cbi.matchat.org/matcher_service"
      - "CLUSTER_SEEDNODES=satvm06.researchstudio.at:2561,satvm06.researchstudio.at:2562"
      - "URI_SPARQL_ENDPOINT=http://satvm06.researchstudio.at:10000/blazegraph/namespace/kb/sparql"
      - "WONNODECONTROLLER_WONNODE_CRAWL=https://cbi.matchat.org/won/resource,https://node.matchat.org/won/resource" # crawl uki won node and matchat won node
      - "CLUSTER_LOCAL_PORT=2561"
      - "JMEM_OPTS=-XX:+HeapDumpOnOutOfMemoryError"
    ports:
      - "2561:2561"
    volumes:
      - $base_folder/won-client-certs/matcher_service:/usr/src/matcher-service/client-certs/
    depends_on:
      - bigdata
      - wonnode

  # solr server as an atom index
  solr:
    restart: always
    build: ../../image/solr
    volumes:
      - $base_folder/solr/won/data:/opt/solr/server/solr/won/data
      - $base_folder/solr/wontest/data:/opt/solr/server/solr/wontest/data
    ports:
      - "8984:8983"

  # solr matcher and connect to matcher service
  matcher_solr:
    restart: always
    build: ../../image/matcher-solr
    environment:
      - "NODE_HOST=satvm06.researchstudio.at"
      - "CLUSTER_SEEDNODES=satvm06.researchstudio.at:2561,satvm06.researchstudio.at:2562"
      - "CLUSTER_LOCAL_PORT=2562"
      - "MATCHER_SOLR_URI_SOLR_SERVER=http://satvm06.researchstudio.at:8984/solr/"
      - "MATCHER_SOLR_URI_SOLR_SERVER_PUBLIC=http://satvm06.researchstudio.at:8984/solr/"
      - "JMEM_OPTS=-XX:+HeapDumpOnOutOfMemoryError"
    ports:
      - "2562:2562"
    depends_on:
      - solr
      - matcher_service

  # mongodb for persistent debug bot
  mongodb:
    restart: always
    image: tutum/mongodb:3.2
    environment:
      - "MONGODB_USER=won"
      - "MONGODB_DATABASE=uki_bot"
      - "MONGODB_PASS=$mongo_db_passwd"
    ports:
      - "27017:27017"
      - "28017:28017"
    volumes:
      - $base_folder/mongodb/data/db:/data/db

  # debug bot used to test atom communication, connect to wonnodes 1 and 2
  debug_bot:
    restart: always
    image: webofneeds/won-debugbot:latest
    environment:
      - "WON_KEYSTORE_DIR=/usr/src/bots/client-certs/"
      - "WON_NODE_URI=https://cbi.matchat.org/won"
      - "URI_PREFIX_OWNER=https://cbi.matchat.org/debug_bot" # set this for the trust store alias
      - "BOTCONTEXT_IMPL=mongoBotContext"
      - "BOTCONTEXT_MONGODB_USER=won"
      - "BOTCONTEXT_MONGODB_PASS=$mongo_db_passwd"
      - "BOTCONTEXT_MONGODB_HOST=satvm06.researchstudio.at"
      - "BOTCONTEXT_MONGODB_PORT=27017"
      - "BOTCONTEXT_MONGODB_DATABASE=uki_bot"
    volumes:
      - $base_folder/won-client-certs/debug_bot:/usr/src/bots/client-certs/
    depends_on:
      - wonnodeblue
      - wonnodegreen
      - mongodb

  matcher_sparql:
    restart: always
    build: ../../image/matcher-sparql
    image: webofneeds/matcher_sparql:int
    environment:
    - "NODE_HOST=satvm06.researchstudio.at"
    - "CLUSTER_SEEDNODES=satvm06.researchstudio.at:2561,satvm06.researchstudio.at:2562"
    - "CLUSTER_LOCAL_PORT=2563"
    - "MATCHER_SPARQL_URI_SPARQL_ENDPOINT=http://satvm06.researchstudio.at:10000/blazegraph/namespace/kb/sparql"
    - "MATCHER_SPARQL_URI_PUBLIC=http://satvm06.researchstudio.at/sparql/"
    - "JMEM_OPTS=-XX:+HeapDumpOnOutOfMemoryError"
    ports:
    - "2563:2563"
    depends_on:
    - matcher_service
    volumes:
    - $base_folder/won-client-certs/matcher_sparql:/usr/src/matcher-sparql/client-certs/
