version: "2"
services:
  # letsencrypt container that helps renew the matchat.org (including www.match.org and node.matchat.org) certificate.
  # It is used by the nginx (external matchat representation of owner) and the wonnode.
  # This is used once a day by a cronjob on satvm01 to check and renew the certificate.
  # To renew the certificate note the following things:
  # - all involved containers (letsencrypt, nginx, wonnode) are configured to mount the right folders
  # - the certificate folder on the host is configured to be "$base_folder/letsencrypt/certs/live/matchat.org"
  # - nginx must be running so that the acme challenge can be executed
  #   (for a new creation of the certificate you can start nginx with the nginx-http-only.conf which doesnt need
  #   certificate file for startup)
  # - execute "docker start livesatvm01_letsencrypt_1" for certificate renewal on host satvm01
  # - this should renew the letsencrypt certificate in "$base_folder/letsencrypt/certs/live/matchat.org" on the host
  # - check if the .pem files and the java key store files (.jks and .pfx) in the same folder have also been updated
  # - delete all (trust store) files in directory $base_folder/won-client-certs/ on all hosts (satvm01)
  # - redeploy all live containers (with jenkins job)
  # - check if everything works (HTTPS, websocket and JMS communication)
  letsencrypt:
    build: ../../image/letsencrypt
    image: webofneeds/letsencrypt:live
    environment:
      - "KEY_STORE_PASSWORD=$won_certificate_passwd"
    volumes:
      - $base_folder/letsencrypt/certs:/etc/letsencrypt
      - $base_folder/letsencrypt/acme-challenge:/usr/share/nginx/html

  # owner server self-signed certificate for communication with wonnode
  gencert:
    build: ../../image/gencert
    image: webofneeds/gencert:live
    environment:
      - "CN=matchat.org"
      - "PASS=file:/usr/local/certs/out/won_certificate_passwd_file"
      - "OPENSSL_CONFIG_FILE=/usr/local/openssl.conf"
    volumes:
      - $base_folder/won-server-certs:/usr/local/certs/out/
      - $base_folder/openssl.conf:/usr/local/openssl.conf

  # nginx proxy server for domains: matchat.org, www.matchat.org, node.matchat.org, uki.matchat.org, node.uki.matchat.org
  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
      - "443:443"
      - "61616:61616"
      - "61626:61626"
      - "61611:61611"
      - "61612:61612"
      - "61613:61613"
    volumes:
      - $base_folder/letsencrypt/certs:/etc/letsencrypt/
      - $base_folder/nginx.conf:/etc/nginx/nginx.conf
      - $base_folder/nginx-uki-http.conf:/etc/nginx/conf.d/nginx-uki-http.conf
      - $base_folder/letsencrypt/acme-challenge:/usr/share/nginx/html/
      - /data/osmcache/
    depends_on:
      - gencert

  # postgres atom databases for wonnode
  postgres_node:
    restart: always
    image: webofneeds/postgres:live
    build: ../../image/postgres
    environment:
      - "POSTGRES_PASSWORD=$postgres_db_passwd"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    volumes:
      - $base_folder/postgres_node/data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"

  # wonnode with nginx proxy => https://node.matchat.org
  wonnode:
    restart: always
    build: ../../image/wonnode
    image: webofneeds/wonnode:live
    environment:
      - "URI_HOST=node.matchat.org"
      - "URI_PREFIX=https://node.matchat.org/won"
      - "HTTP_PORT=8443"
      - "DB_SQL_JDBCDRIVERCLASS=org.postgresql.Driver"
      - "DB_SQL_JDBCURL=jdbc:postgresql://satvm01.researchstudio.at:5433/won_node"
      - "DB_DDL_STRATEGY=validate"
      - "DB_SQL_USER=won"
      - "DB_SQL_PASSWORD=$postgres_db_passwd"
      - "CERTIFICATE_PASSWORD=$won_certificate_passwd"
      - "ACTIVEMQ_BROKER_PORT=61616"
      - "CLIENT_AUTHENTICATION_BEHIND_PROXY=true"
      - "JMEM_OPTS=-XX:+HeapDumpOnOutOfMemoryError"
      - "JMX_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,address=*:62918,server=y,suspend=n
      -Dcom.sun.management.jmxremote.port=9018 -Dcom.sun.management.jmxremote.authenticate=false
      -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=9018
      -Djava.rmi.server.hostname=satvm01.researchstudio.at"
    ports:
      - "8443:8443"
      - "61617:61616"
      - "62918:62918"
      - "9018:9018"      
    volumes:
      - $base_folder/letsencrypt/certs/live/matchat.org/fullchain.pem:/usr/local/tomcat/conf/ssl/t-cert.pem
      - $base_folder/letsencrypt/certs/live/matchat.org/privkey.pem:/usr/local/tomcat/conf/ssl/t-key.pem
      - $base_folder/letsencrypt/certs/live/matchat.org/t-key-cert.pfx:/usr/local/tomcat/conf/ssl/t-key-cert.pfx
      - $base_folder/letsencrypt/certs/live/matchat.org/t-keystore.jks:/usr/local/tomcat/conf/ssl/t-keystore.jks
      - $base_folder/won-client-certs/wonnode:/usr/local/tomcat/won/client-certs/
    depends_on:
      - postgres_node
      - nginx

  # postgres atom databases for owner
  postgres_owner:
    restart: always
    image: webofneeds/postgres:live
    build: ../../image/postgres
    environment:
      - "POSTGRES_PASSWORD=$postgres_db_passwd"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    volumes:
      - $base_folder/postgres_owner/data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  # owner with nginx proxy (https://www.matchat.org)
  owner:
    restart: always
    build: ../../image/owner
    image: webofneeds/owner:live
    environment:
      - "NODE_DEFAULT_HOST=node.matchat.org"
      - "URI_HOST=www.matchat.org"
      - "HTTP_PORT=8082"
      - "NODE_DEFAULT_HTTP_PORT=443"
      - "URI_PREFIX=https://www.matchat.org"
      - "URI_PREFIX_NODE_DEFAULT=https://node.matchat.org/won"
      - "DB_SQL_JDBCDRIVERCLASS=org.postgresql.Driver"
      - "DB_SQL_JDBCURL=jdbc:postgresql://satvm01.researchstudio.at:5432/won_owner"
      - "DB_DDL_STRATEGY=validate"
      - "DB_SQL_USER=won"
      - "DB_SQL_PASSWORD=$postgres_db_passwd"
      - "CERTIFICATE_PASSWORD=$won_certificate_passwd"
      - "OWNER_WEBAPP_REMEMBERME_KEY=$rememberme_key"
      - "EMAIL_FROM_WON_USER=$MAIL_USER"
      - "EMAIL_FROM_WON_PASSWORD=$MAIL_PASS"
      - "EMAIL_FROM_WON_SMTP_HOST=$MAIL_HOST"
      - "JMEM_OPTS=-XX:+HeapDumpOnOutOfMemoryError"
      - "JMX_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,address=*:62919,server=y,suspend=n"
    ports:
      - "8082:8443"
    volumes:
      - $base_folder/custom_owner_skin:/usr/local/tomcat/webapps/owner/skin/current/
      - $base_folder/won-server-certs:/usr/local/tomcat/conf/ssl/
      - $base_folder/won-client-certs/owner:/usr/local/tomcat/won/client-certs/
    depends_on:
      - postgres_owner
      - gencert

  # bigdata rdf store for matcher service (this image is not built at deployment, it is downloaded from dockerhub)
  bigdata:
    restart: always
    build: ../../image/bigdata
    volumes:
      - $base_folder/bigdata/data/:/usr/src/bigdata/data
    ports:
      - "10000:9999"

  # matcher service connect with wonnode on (proxied: node.matchat.org)
  matcher_service:
    restart: always
    build: ../../image/matcher-service
    image: webofneeds/matcher_service:live
    environment:
      - "NODE_HOST=satvm01.researchstudio.at"
      - "MATCHER_URI=https://matchat.org/matcher_service"
      - "CLUSTER_SEEDNODES=satvm01.researchstudio.at:2561,satvm01.researchstudio.at:2562"
      - "URI_SPARQL_ENDPOINT=http://satvm01.researchstudio.at:10000/blazegraph/namespace/kb/sparql"
      - "WONNODECONTROLLER_WONNODE_CRAWL=https://node.matchat.org/won/resource"
      - "CLUSTER_LOCAL_PORT=2561"
      - "JMEM_OPTS=-XX:+HeapDumpOnOutOfMemoryError"
    ports:
      - "2561:2561"
    volumes:
      - $base_folder/won-client-certs/matcher_service:/usr/src/matcher-service/client-certs/
    depends_on:
      - bigdata
      - wonnode

  # solr server as an atom index
  solr:
    restart: always
    build: ../../image/solr
    image: webofneeds/solr:live
    volumes:
      - $base_folder/solr/won/data:/opt/solr/server/solr/won/data
      - $base_folder/solr/wontest/data:/opt/solr/server/solr/wontest/data
    ports:
      - "8984:8983"

  # solr matcher and connect to matcher service
  matcher_solr:
    restart: always
    build: ../../image/matcher-solr
    image: webofneeds/matcher_solr:live
    environment:
      - "NODE_HOST=satvm01.researchstudio.at"
      - "CLUSTER_SEEDNODES=satvm01.researchstudio.at:2561,satvm01.researchstudio.at:2562"
      - "CLUSTER_LOCAL_PORT=2562"
      - "MATCHER_SOLR_URI_SOLR_SERVER=http://satvm01.researchstudio.at:8984/solr/"
      - "MATCHER_SOLR_URI_SOLR_SERVER_PUBLIC=http://satvm01.researchstudio.at:8984/solr/"
      - "JMEM_OPTS=-XX:+HeapDumpOnOutOfMemoryError"
    ports:
      - "2562:2562"
    depends_on:
      - solr
      - matcher_service

  # rescal matcher and connect to matcher service
#  matcher_rescal:
#    restart: always
#    build: ../../image/matcher-rescal
#    image: webofneeds/matcher_rescal:live
#    environment:
#      - "NODE_HOST=satvm01.researchstudio.at"
#      - "CLUSTER_SEEDNODES=satvm01.researchstudio.at:2561,satvm01.researchstudio.at:2563"
#      - "CLUSTER_LOCAL_PORT=2563"
#      - "MATCHER_RESCAL_URI_PUBLIC=http://satvm01.researchstudio.at/rescal/"
#      - "MATCHER_RESCAL_URI_SPARQL_ENDPOINT=http://satvm01.researchstudio.at:10000/blazegraph/namespace/kb/sparql"
#      - "MATCHER_RESCAL_EXECUTIONDURATIONMINUTES=30"
#      - "MATCHER_RESCAL_THRESHOLD=0.2"
#      - "MATCHER_RESCAL_RANK=10"
#      - "JMEM_OPTS=-XX:+HeapDumpOnOutOfMemoryError"
#    ports:
#      - "2563:2563"
#    depends_on:
#      - bigdata
#      - matcher_service

  # mongodb for persistent debug bot
  mongodb:
    restart: always
    image: tutum/mongodb:3.2
    environment:
      - "MONGODB_USER=won"
      - "MONGODB_DATABASE=live_bot"
      - "MONGODB_PASS=$mongo_db_passwd"
    ports:
      - "27017:27017"
      - "28017:28017"
    volumes:
      - $base_folder/mongodb/data/db:/data/db

  # debug bot used to test atom communication, connect to wonnode
  debug_bot:
    restart: always
    image: webofneeds/won-debugbot:latest
    environment:
      - "WON_KEYSTORE_DIR=/usr/src/bots/client-certs/"
      - "WON_NODE_URI=https://node.matchat.org/won"
      - "URI_PREFIX_OWNER=https://matchat.org/debug_bot" # set this for the trust store alias
      # - "WON_NODE_URIS=https://node.matchat.org/won/resource" #not necessary because the WON_NODE_URI is added by default if nothing is set
      - "BOTCONTEXT_IMPL=mongoBotContext"
      - "BOTCONTEXT_MONGODB_USER=won"
      - "BOTCONTEXT_MONGODB_PASS=$mongo_db_passwd"
      - "BOTCONTEXT_MONGODB_HOST=satvm01.researchstudio.at"
      - "BOTCONTEXT_MONGODB_PORT=27017"
      - "BOTCONTEXT_MONGODB_DATABASE=live_bot"
    volumes:
      - $base_folder/won-client-certs/debug_bot:/usr/src/bots/client-certs/
    depends_on:
      - wonnode
      - mongodb

#  spoco_raid_bot:
#    restart: always
#    image: webofneeds/won-spoco-raidbot:latest
#    environment:
#      - "WON_KEYSTORE_DIR=/usr/src/bots/client-certs/"
#      - "WON_NODE_URI=https://node.matchat.org/won"
#      # - "LOGGING_CONFIG=/usr/src/bots/logback.xml"
#      - "URI_PREFIX_OWNER=https://matchat.org/raid_bot" # set this for the trust store alias
#      - "API_LINZ_ENDPOINT=$RB_ENDPOINT_LINZ"
#      - "API_LINZ_TOKEN=$RB_TOKEN_LINZ"
#      - "API_VIENNA_ENDPOINT=$RB_ENDPOINT_VIENNA"
#      - "API_VIENNA_USERNAME=$RB_USER_VIENNA"
#      - "API_VIENNA_REQUEST=$RB_REQUEST_VIENNA"
#      - "RAIDBOT_FETCHINTERVAL=600" #fetch new raids every 600 seconds (10min)
#      - "RAIDBOT_SANITIZEINTERVAL=900" #sanitize existing raids every 900 seconds (15min)
#      - "BOTCONTEXT_IMPL=mongoBotContext"
#      - "BOTCONTEXT_MONGODB_USER=won"
#      - "BOTCONTEXT_MONGODB_PASS=$mongo_db_passwd"
#      - "BOTCONTEXT_MONGODB_HOST=satvm01.researchstudio.at"
#      - "BOTCONTEXT_MONGODB_PORT=27017"
#      - "BOTCONTEXT_MONGODB_DATABASE=live_bot"
#      # - "RAIDBOT_PHASEOUT=true" # set this if you do not want to create new atoms but just manage the existing ones
#    volumes:
#      - $base_folder/won-client-certs/raid_bot:/usr/src/bots/client-certs/
#    #     - $base_folder/logback_debug_bot.xml:/usr/src/bots/logback.xml
#    depends_on:
#      - mongodb
#      - wonnode


  # job bot connecting hokify to WoN

#  hokify_bot:
#    restart: always
#    image: webofneeds/won-jobbot:latest
#    environment:
#      - "WON_KEYSTORE_DIR=/usr/src/bots/client-certs/"
#      - "WON_NODE_URI=https://node.matchat.org/won"
#      #      - "LOGGING_CONFIG=/usr/src/bots/logback.xml"
#      - "URI_PREFIX_OWNER=https://matchat.org/hokify_bot" # set this for the trust store alias
#      - "HOKIFYJOBBOT_JSONURL=https://hokify.at/jobfeed-webofneeds.json/"
#      - "HOKIFYJOBBOT_GEOURL=https://nominatim.openstreetmap.org/search"
#      - "HOKIFYJOBBOT_UPDATETIME=70"
#      - "HOKIFYJOBBOT_PUBLISHTIME=10"
#      - "HOKIFYJOBBOT_CREATEALLINONE=false"
#      - "BOTCONTEXT_IMPL=mongoBotContext"
#      - "BOTCONTEXT_MONGODB_USER=won"
#      - "BOTCONTEXT_MONGODB_PASS=$mongo_db_passwd"
#      - "BOTCONTEXT_MONGODB_HOST=satvm01.researchstudio.at"
#      - "BOTCONTEXT_MONGODB_PORT=27017"
#      - "BOTCONTEXT_MONGODB_DATABASE=live_bot"
#    volumes:
#      - $base_folder/won-client-certs/hokify_bot:/usr/src/bots/client-certs/
#    #     - $base_folder/logback_debug_bot.xml:/usr/src/bots/logback.xml
#    depends_on:
#      - mongodb
#      - wonnode

  # MySQL database for piwik
  mysql:
    restart: always
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - $base_folder/mysql/data:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=$mysql_passwd"

  # piwik tool for analytics
  piwik:
    restart: always
    image: piwik:latest
    ports:
      - "8080:80"
    volumes:
      - $base_folder/piwik/config:/var/www/html/config
    depends_on:
      - mysql

  matcher_sparql:
    restart: always
    build: ../../image/matcher-sparql
    image: webofneeds/matcher_sparql:int
    environment:
      - "NODE_HOST=satvm01.researchstudio.at"
      - "CLUSTER_SEEDNODES=satvm01.researchstudio.at:2561,satvm01.researchstudio.at:2563"
      - "CLUSTER_LOCAL_PORT=2564"
      - "MATCHER_SPARQL_URI_SPARQL_ENDPOINT=http://satvm01.researchstudio.at:10000/blazegraph/namespace/kb/sparql"
      - "MATCHER_SPARQL_URI_PUBLIC=http://satvm01.researchstudio.at/sparql/"
      - "JMEM_OPTS=-XX:+HeapDumpOnOutOfMemoryError"
    ports:
      - "2564:2564"
    depends_on:
      - matcher_service
    volumes:
      - $base_folder/won-client-certs/matcher_sparql:/usr/src/matcher-sparql/client-certs/
