version: "2"
services:
  # owner server self-signed certificate for communication with wonnode
  gencert:
    build: ../../image/gencert
    #image: webofneeds/gencert:master
    environment:
      - "CN=spoco.me"
      - "PASS=file:/usr/local/certs/out/won_certificate_passwd_file"
      - "OPENSSL_CONFIG_FILE=/usr/local/openssl.conf"
    volumes:
      - $base_folder/won-server-certsspoco:/usr/local/certs/out/
      - $base_folder/openssl.conf:/usr/local/openssl.conf

  # portsgres atom databases for owner and wonnode
  postgres:
    restart: always
    image: webofneeds/postgres:master
    #build: ../../image/postgres
    environment:
      - "POSTGRES_PASSWORD=$postgres_db_passwd"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    volumes:
      - $base_folder/postgres/data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5435:5435"

  # owner => https://spoco.matchat.org/owner -> spoco.me
  owner:
    restart: always
    build: ../../image/owner
    #image: webofneeds/owner:master
    environment:
      - "NODE_DEFAULT_HOST=node.matchat.org"
      - "URI_HOST=spoco.me"
      - "HTTP_PORT=8084"
      - "NODE_DEFAULT_HTTP_PORT=443"
      - "URI_PREFIX=https://spoco.me"
      - "URI_PREFIX_NODE_DEFAULT=https://node.matchat.org/won"
      - "DB_SQL_JDBCDRIVERCLASS=org.postgresql.Driver"
      - "DB_SQL_JDBCURL=jdbc:postgresql://satvm02.researchstudio.at:5434/won_owner"
      - "DB_DDL_STRATEGY=validate"
      - "DB_SQL_USER=won"
      - "DB_SQL_PASSWORD=$postgres_db_passwd"
      - "CERTIFICATE_PASSWORD=$won_certificate_passwd"
      - "EMAIL_FROM_WON_USER=$MAIL_USER"
      - "EMAIL_FROM_WON_PASSWORD=$MAIL_PASS"
      - "EMAIL_FROM_WON_SMTP_HOST=$MAIL_HOST"
      - "JMEM_OPTS=-XX:+HeapDumpOnOutOfMemoryError"
      - "JMX_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,address=*:62928,server=y,suspend=n
        -Dcom.sun.management.jmxremote.port=9032 -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=9032
        -Djava.rmi.server.hostname=satvm02.researchstudio.at"
    ports:
      - "8084:8443"
      - "62928:62928"
      - "9032:9032"
    volumes:
      - $base_folder/custom_owner_skin:/usr/local/tomcat/webapps/owner/skin/current/
      - $base_folder/won-server-certsspoco:/usr/local/tomcat/conf/ssl/
      - $base_folder/won-client-certs/spoco:/usr/local/tomcat/won/client-certs/
    depends_on:
      - postgres
      - gencert
